networks:
  default:
    name: wallet_net

name: wallet

services:
  db:
    image: postgres:14.0-alpine
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 25s
    ports:
      - "5432:5432"

  web:
    build:
      context: ../
      dockerfile: environment/Dockerfile
      target: development
    env_file: .env
    command: dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../src:/home/application/current
