# Generated by Django 5.2.7 on 2025-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwallettransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Error'), (1, 'Testing'), (2, 'Deposit'), (3, 'Withdraw')], default=1, help_text='Add or substract money'),
        ),
    ]
